### ISSUE TITLE
Terminating resolver before other nodes makes other nodes hang on shutdown

### ISSUE THREAD

**Issue by fferri** [blueworkforce/bluezero#1]
If terminating resolver nodes before terminating other nodes, when terminating the other nodes (with CTRL+C) those hang on the line
```
^C[NODENAME] {main} DEBUG: Killing heartbeat thread...
```

**Comment by MariusRaduGheorghe** [comment]
Unfortunately, this fix created a problem on slow networks.
Here is the stacktrace:

>1 raise 0x7ffff6d72428 
2 abort  0x7ffff6d7402a 
3  __gnu_cxx::__verbose_terminate_handler() 0x7ffff73ac7dd 
4  ?? 0x7ffff73aa6b6 
5  std::terminate()   0x7ffff73aa701 
6  __cxa_throw   0x7ffff73aa919 
7  b0::Socket::readRaw   socket.cpp   122 0x7fffc5b20051 
8  b0::protobuf::SocketProtobuf::read   socket.cpp   14  0x7fffc5b3311d 
9  b0::protobuf::ServiceClient<b0::resolver_msgs::Request, b0::resolver_msgs::Response>::call   service_client.h   48  0x7fffc5b3617e 
10 b0::resolver::Client::sendHeartbeat   client.cpp   100 0x7fffc5b343f8 
11 b0::Node::heartbeatLoop   node.cpp   324 0x7fffc5b067a5 
12 boost::_mfi::mf0<void, b0::Node>::operator()   mem_fn_template.hpp 49  0x7fffc5b1f6d9 
13 boost::_bi::list1<boost::_bi::value<b0::Node *>>::operator()<boost::_mfi::mf0<void, b0::Node>, boost::_bi::list0>   bind.hpp   253 0x7fffc5b1f63c 
14 boost::_bi::bind_t<void, boost::_mfi::mf0<void, b0::Node>, boost::_bi::list1<boost::_bi::value<b0::Node *>>>::operator()   bind.hpp   893 0x7fffc5b1f26e 
15 boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, b0::Node>, boost::_bi::list1<boost::_bi::value<b0::Node *>>>>::run thread.hpp   116 0x7fffc5b1e18c 
16 ??   0x7fffc4dbc5d5 
17 start_thread   pthread_create.c   333 0x7ffff681e6ba 
18 clone   0x7ffff6e4441d

**Comment by fferri** [comment]
Right. This fix introduced a new problem in case of degraded (very slow) networks.

And anyway, the premise (_shutting down the resolver before other nodes_) doesn't really make sense.

So I'm going to revert this fix (both in v1 and in v2).

**Comment by fferri** [comment]
Try with commit 316c449 (fix backported from v2 branch).

**Comment by fferri** [comment]
Reopen if this issue remains unresolved.
