### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by windelbouwman** [blueworkforce/bluezero#3]
Hi!

Compliments on this project. This is exactly what we need. Some simple framework with pub/sub and services like ROS, but not as bloated/large as ROS. I checked out the project, but got a build failure on an example. I fixed the error locally, it was a simple one. Do you plan to add travis CI?

Regards,
Windel

**Comment by fferri** [comment]
Not in the current plans, but if you want to add it, PRs are welcome. :-)
